keys:
- &recover age10esr5rnqjm976hznam6mx2gzx25j8z5nm5vj9ty9wegqev8prcas5azfgh
- &desktop_home age10dvc02fthz48jlxq8nrq2xsu7sgruhxh233pe8y3xn623nyc3d0qjwrm9n
- &laptop_home age1qe8ys0rvc9jkr2n88k7rarnqttr4j00aqc5jpkd7u4dprz20vvmsvcetjp
creation_rules:
- path_regex: secrets/users/xing/.*$
  key_groups:
  - age:
    - *recover
    - *desktop_home
    - *laptop_home
