add_newline = true
format = """
$directory\
$nix_shell\
$git_branch\
$git_commit\
$git_status\
$aws\
$kubernetes\
$line_break\
$character"""

[kubernetes]
format = 'on [⛵ $context \($namespace\)](dimmed green) '
disabled = false

[character]
success_symbol = "[➜](bold green)"
error_symbol = "[✗](bold red)"

[aws]
symbol = " "

[battery]
full_symbol = ""
charging_symbol = ""
discharging_symbol = ""

[conda]
symbol = " "

[docker_context]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[git_branch]
symbol = " "

[golang]
symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[memory_usage]
symbol = " "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "

[package]
symbol = " "

[php]
symbol = " "

[python]
symbol = " "

[ruby]
symbol = " "

[rust]
symbol = " "
